name: Trigger auto deployment for container-app-oxhcw7qxnbihu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ node-create-base ]
    paths:
    - 'api/**'
    - '.github/workflows/container-app-oxhcw7qxnbihu-AutoDeployTrigger-067b3a55-e7e4-4099-b774-5e79faf82794.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOXHCW7QXNBIHU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOXHCW7QXNBIHU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOXHCW7QXNBIHU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOXHCW7QXNBIHU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOXHCW7QXNBIHU_REGISTRY_PASSWORD }}
          containerAppName: container-app-oxhcw7qxnbihu
          resourceGroup: e2etests84bb
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


