name: Trigger auto deployment for e2etests9f5f9b48

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dotnet-create-base ]
    paths:
    - 'api/**'
    - '.github/workflows/e2etests9f5f9b48-AutoDeployTrigger-07e71f8f-93ce-44ea-a360-5d7bec6b4d1b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.E2ETESTS9F5F9B48_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.E2ETESTS9F5F9B48_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.E2ETESTS9F5F9B48_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api 
          registryUrl: 
          registryUsername: ${{ secrets.E2ETESTS9F5F9B48_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.E2ETESTS9F5F9B48_REGISTRY_PASSWORD }}
          containerAppName: e2etests9f5f9b48
          resourceGroup: e2etests9f5f
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


